Added python interface for multiple start indices
leonardodalinky/fpsample pull request #5
Opened 2024-11-04 09:17 UTC by PhilippDahlinger

- Correct typing
- assert statement to check that start list <= num_samples
- conversion to unsigned int np array

Added rust wrappers to handle multiple start indices
- New start_idx enum to handle both cases
- Added Rust input check
- Rust interface setup for implementing multi start index algorithms.

2024-11-05 06:30 UTC, leonardodalinky requested changes
Do you try to compile the code and test if the NotImplementError occurs?

I think the `StartIndex` enum should derive the `#[derive(FromPyObject)]` features as described in [pyo3-doc](https://pyo3.rs/v0.22.5/conversions/traits) and [an example here](https://users.rust-lang.org/t/closest-implementation-for-enums-with-fields-in-pyo3/89385/7), if the `StartIndex` wrapper seems to be more fancy.

Though, I may choose to simply change the `start_idx` to a single list in the Python interface to avoid the wrapper and complex if-else/match conditions in Rust.

Anyways, both way is OK to me.

2024-11-05 11:50 UTC, PhilippDahlinger commented
I didn't want to make any interface changes to the existing code, so I chose the enum. I compiled the code and the NotImplementedError occurs (after fixing some rust stuff), when provided the start index list. The tests still pass when using no start idx or a single start index.

2024-11-06 04:34 UTC, leonardodalinky requested changes
Seems good to me with only minor errors. Do you want to support multiple start indices to all functions here?

2024-11-06 04:34 UTC, leonardodalinky commented on bench/test_bench.py
Function name `test_vanilla_fps_4k`  is already in use. Try another name like `test_vanilla_fps_4k_multiple`.

2024-11-06 08:28 UTC, PhilippDahlinger commented on bench/test_bench.py
Thanks, I changed it.

2024-11-06 08:32 UTC, PhilippDahlinger commented
Thanks! Well, its my first contact with Rust, but it looks like a nice language, I might want to learn it. Ideally, It would be nice to have multiple start indices for all fps functions, but if you could only start with `KDTree-based FPS` or `Bucket-based FPS`, I would be already completely happy, since then I can use it already in my current work. For my problem, both work very well and are really fast.

2024-11-07 04:10 UTC, merged

2024-11-07 04:11 UTC, leonardodalinky commented
OK，I would try to make these features at this weekend. :)

2024-11-07 04:12 UTC, leonardodalinky reviewed
LGTM.